### ISSUE TITLE
Support for Dropwizard 3.0

### ISSUE THREAD

**Issue by sureshms** [dropwizard/dropwizard-health#164]
Would love to see Dropwizard 3.0 support added. In 3.0 Dropwizard has reorganized the classes into different packages. For example `io.dropwizard.Configuration` to `io.dropwizard.core.Configuration`.

**Comment by joschi** [comment]
Dropwizard Health is part of the Dropwizard main project since [Dropwizard 2.1.0](https://github.com/dropwizard/dropwizard/releases/tag/v2.1.0). 😉
